
path: C:\Users\IT\Documents\Learn Image CLasifier\test3\code\data  # dataset root dir
train: images\train  # train images (relative to 'path')
val: images\val  # val images (relative to 'path')

# Classes
#nc : 3
#names: ['head','helmet','person']
names:
  0 : head
  1 : person
  2 : helmet 